### ISSUE TITLE
Equator crossing times and longitudes in 3a files are incorrect; radscolin fails

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#101]
The equator crossing information extracted from the standard_measurements.nc files by s3combine has two errors. 1) ascending passes repeat the previous pass information (i.e. the previous orbit's ascending pass) and 2) descending passes contains the previous ascending pass's information.

These errors cause radscolin to fail: 
radscolin4: Skipping pass because of rogue timings (time(:) or equator_time)

**Comment by remkos** [comment]
I tried to do it right, but the original granules are themselves often wrong on which orbit they belong too, because they appear to copy the info from the original dump, which may have started in the previous orbit. I'll have to make the process smarter to avoid this problem. I can work on that a bit, or have you already pinpointed the culprit.

**Comment by remkos** [comment]
This should be fixed in revision 1a3e3fd.
This patch adds to the output file in "predicted" equator time and longitude based on the information in the rads.xml file. This will satisfy most purposes.
Also it makes updates to the start and end time and longitude as well, which was not done before.

Please check if this patch works, and close the issue if so.

Sorry, you'll have to recreate all your combined granules with the updated software.

**Comment by leuliett** [comment]
eqlon is now correct.
eqtime lags by 1/2 orbit.
Perhaps we need a "+1" in:
P%equator_time = S%phase%ref_time + ((cc - S%phase%ref_cycle) \* S%phase%repeat_passes + (pp **\+ 1** - S%phase%ref_pass)) \* d

A handful of "short" passes have equator_time = "1985-01-01 00:00:00.000000" ;

# Statistics of RADS variables (box weight)

# Created: 2016-08-17 15:48:40 UTC: radsstat4 -S3a -p -Veqtime,dtime,lon,eqlon

#

# Satellite : 3a/a

# Cycles    :    0 -   99

# Passes    :    1 -  770

#

# Output columns:

# ( 1, 2) cycle and pass

# ( 3) nr of measurements

# ( 4) mean time [seconds since 1985-01-01 00:00:00 UTC]

# ( 5- 6) mean and stddev of time of equator crossing [seconds since 1985-01-01]

# ( 7- 8) mean and stddev of longitude [degrees_east]

# ( 9-10) mean and stddev of longitude of equator crossing [degrees_east]

  7  622        8  997979628. 997976600.9610388        20.9489175    3026.53896       2.44949  -98.4706924    0.0320374  261.4942860    0.0000000
  7  623        8  997982662.         0.0000000         0.0000000 ************\*       0.00000   68.8861938    0.0320372   68.8709090    0.0000000
  7  624        8  997985686. 997982660.1818180         0.0000000    3026.31818       2.44949 -123.7142213    0.0320408  236.2475320    0.0000041
  7  625        8  997988720.         0.0000000         0.0000000 ************\*       0.00000   43.6430900    0.0320406   43.6241560    0.0000000
  7  626        9  997991746. 997988719.4025972         0.0000000    3026.59740       2.73861 -148.9651339    0.0358275  211.0007790    0.0000000
  7  628        9  997997805. 997994778.6233770         0.0000000    3026.37662       2.73861 -174.2094838    0.0358310  185.7540260    0.0000000
  7  629        9  998000839.         0.0000000         0.0000000 ************\*      12.00000   -6.8508490    0.0358293  353.1306490    0.0000000
  7  630        9  998003864. 998000837.8441560         0.0000000    3026.15584       2.73861  160.5457722    0.0358323  160.5072730    0.0000029
  7  631        9  998006898.         0.0000000         0.0000000 ************\*       0.00000  -32.0952590    0.0358284  327.8838960    0.0000000
  7  632        8  998009924. 998006897.0649348        17.1047195    3026.43507       2.44949  135.2942209    0.0320462  135.2605190    0.0000029
  7  635        8  998019016. 998015985.8961040         0.0000000    3030.60390       2.44949  -82.5900692    0.0320383  277.3903900    0.0000000
  7  636        9  998022042. 998019015.5064927        26.8328157    3026.49351       2.73861   84.8020492    0.0358200   84.7670130    0.0000000
  7  637        9  998025076.         0.0000000         0.0000000 ************\*      12.00000 -107.8385579    0.0358190  252.1436360    0.0000000
  7  638        9  998028101. 998025074.7272729        24.0000000    3026.27273       2.73861   59.5590120    0.0358202   59.5202600    0.0000007
  7  639        9  998031135.         0.0000000         0.0000000 ************\*       0.00000 -133.0820584    0.0358215  226.8968830    0.0000050
  7  641        8  998037194.         0.0000000         0.0000000 ************\*       0.00000 -158.3330675    0.0320438  201.6501300    0.0000000
  7  642        8  998040220. 998037193.1688310         0.0000000    3026.33117       2.44949    9.0641700    0.0320442    9.0267530    0.0000000
  7  643        8  998043254.         0.0000000         0.0000000 ************\*       0.00000  176.4219657    0.0320459  176.4033770    0.0000000
  7  644        8  998046278. 998043252.3896102         0.0000000    3026.11039       2.44949  -16.1804605    0.0320467  343.7800000    0.0000000
  7  645        8  998049312. 998046282.0000000         0.0000000    3030.50000       2.44949  151.1769690    0.0320455  151.1566230    0.0000020

**Comment by remkos** [comment]
It was not what you suggested. Just a wrong placing of the call to rads_predict_equator.
Please try again.

**Comment by leuliett** [comment]
Both eqtime and eqlon are working correctly now, with eqtime < 4 seconds. radscolin now works for 3a.

**Comment by remkos** [comment]
With the MOE orbit available, we can update the time easily with "rads_add_orbit --equator"
