### ISSUE TITLE
TMPDIR in rads_sandbox.sh

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#103]
Can we switch:
SANDBOX=`mktemp -d ${TMPDIR:-/tmp}/rads.XXXXXX`
to
SANDBOX=`mktemp -d rads.XXXXXX`
?

Because mktemp should already use TMPDIR to override the default on a system, specifying this option is unnecessary. On Linux, /tmp should already be set by default. On macOS, a folder will be chosen in /var/folders. With the current rads_sandbox.sh, there is no way for the default macOS method to be invoked.

**Comment by remkos** [comment]
Unfortunately, `mktemp -d rads.XXXXXX` creates a directory in the **current** directory not in TMPDIR. At least that's the case on MacOS and Linux.

The solution seems to be, on MacOS:
`mktemp -d -t rads`
and on Linux:
`mktemp -d -t rads.XXXXXX`

A bit annoying that they are different. The latter, of course, will work on both platforms, but on MacOS the part .XXXXXX will be included, literally.

**Comment by leuliett** [comment]
We can leave rads_sandbox.sh as is. My issue was resulted from using a crontab which didn't export the default TMPDIR set by macOS and instead TMPDIR was not set. I was able to fix my crontab jobs adding a line to each script that set TMPDIR to the default path to default TMPDIR for the macOS user directory using:

export TMPDIR=`getconf DARWIN_USER_TEMP_DIR`
