### ISSUE TITLE
rads.xml file in working directory

### ISSUE THREAD

**Issue by susanabarbosa** [remkos/rads#105]
I'm sure I'm doing something stupid, but I really can't figure out what... I though I could have a rads.xml file in a working directory (possibly with different options than the one in data/conf), but then I can't extract any data from the database... Here's an example:

i) What I get if I run the rads2grd command from a directory without a rads.xml file

$ rads2grd4 -S tx -C 11 --lon -10,-9 --lat 33,34 --var lon,lat,sla --min 0  

 -10.000000  33.000000   0.0000  -0.0000 0
  -9.000000  33.000000  -0.0516   0.0132 2
 -10.000000  34.000000   0.0000  -0.0000 0
  -9.000000  34.000000  -0.0209   0.0241 10

ii) Then if having a rads.xml file (the same as in data/conf) in the directory
rads2grd4 -S tx -C 11 --lon -10,-9 --lat 33,34 --var lon,lat,sla --min 0  

 -10.000000  33.000000   0.0000  -0.0000 0
  -9.000000  33.000000   0.0000  -0.0000 0
 -10.000000  34.000000   0.0000  -0.0000 0
  -9.000000  34.000000   0.0000  -0.0000 0

I wanted to have the rads.xml file in the working directory in order to edit it and extract SLA's without the IB correction...

Thanks
Susana

**Comment by leuliett** [comment]
Hi Susana,
RADS already includes an XML file to create SLAs without the IB applied. In conf, you should find the file no_inv_bar.xml. It can be included with the -X option:
rads2asc -Stx -C11 --lon -10,-9 --lat 33,34 -Vlon,lat,sla -Xno_inv_bar.xml
It's also a good example of how you can modify the selections in rads.xml
Section 4.3 of the user's manual describes the XML tags that are available.

**Comment by susanabarbosa** [comment]
That's it, many thanks!!!
Susana
