### ISSUE TITLE
rads2nc fails in getting variable "liquid_water_rad" for tx

### ISSUE THREAD

**Issue by hfengg** [remkos/rads#107]
try to use RADS4 commands ( "rads2nc" and "rads2asc4 ) to extract variable "liquid water content"
(field    = 3301) for topex. It comes out with all "zero" values by running

      rads2nc -Stx -C10 -P24 -Isla,liquid_water_rad out='txp0024c010.nc' -r
  rads2asc4 -Stx -C10 -P24 -Vsla,liquid_water_rad out='txp0024c010.asc4' -r

BTW, use of  the RADS3 command "rads2asc" is OK in getting it

Appreciated if any one knows a fix. Thanks 

Hui 
UNH

**Comment by leuliett** [comment]
The problem appears to be that the TX NetCDF files name the variable "liquid_water", while the RADS configuration file (rads.xml) has the field named liquid_water_rad. As a temporary workaround, you can create an XML file named liquid_water.xml with this content:
<var name="liquid_water" field="3301 33" sat="tx">
        <long_name>liquid water content</long_name>
        <standard_name>atmosphere_mass_content_of_cloud_liquid_water</standard_name>
        <units>kg/m^2</units>
        <data>liquid_water</data>
        <default>0</default>
        <format>f6.2</format>
        <compress>int2 1e-2</compress>
</var>

Then add this X flag to your command and use "liquid_water" as the field name:
rads2asc4 -Stx -C10 -P24 -Vsla,liquid_water out='txp0024c010.asc4' -r -Xliquid_water.xml

**Comment by hfengg** [comment]
Thank you Eric Leuliett ,    it works !
