### ISSUE TITLE
Naming issue: liquid_water_rad field in TX and PN

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#108]
The liquid_water_rad field is named liquid_water in TX and PN files. rads.xml doesn't recognize this, so either rads.xml needs to be modified or the field needs to be renamed in the files to make them consistent with the other missions.

**Comment by remkos** [comment]
I have just updated the TX and PN files so that the variable is properly names liquid_water_rad.
The files are making it to the RADS server at this very moment.

**Comment by remkos** [comment]
Correction verified. Upload completed 24.05.2017.
