### ISSUE TITLE
T/P SLCCI orbit problem

### ISSUE THREAD

**Issue by MarcelKleinherenbrink** [remkos/rads#109]
There is a problem with the SLCCI orbits in T/P cycle 355.
Passes 2-248 appear to be affected.

Marcel

**Comment by remkos** [comment]
I have investigated this problem. The input orbit TOPX_20020504_SP3C.gz is time stamped at a very odd time (not integer seconds). Unfortunately, my orbit interpolation software does not cope with anything else than integer seconds. I will have to tweak things a bit to get it right.

**Comment by remkos** [comment]
In fact, there are many orbits produced by GFZ that start at non-integer seconds.
But this does not happen for the GFZ SLCCI orbits of ERS-1, ERS-2, Jason-1, Jason-2, or Envisat.

**Comment by remkos** [comment]
Headers of the TOPEX SLCCI orbits that do not start on integer seconds:
#cV1992 10 12 22 58 59.84637200   34648       CTS   FIT  GFZ
#cV1992 12 21  8 49 44.61118800   21800       CTS   FIT  GFZ
#cV1993  3 30 12 25 52.84692400   10005       CTS   FIT  GFZ
#cV1993  8  6  9 36 12.84480300   16116       CTS   FIT  GFZ
#cV1994  1 31 20 46 30.61488900   17665       CTS   FIT  GFZ
#cV1994  5 20 23 33 29.85325300   20212       CTS   FIT  GFZ
#cV1994 10  6 17 46 19.85407100   23765       CTS   FIT  GFZ
#cV1995  5 22 21 23  2.84876100   29104       CTS   FIT  GFZ
#cV1996  1 15 20 59  2.85033300    6120       CTS   FIT  GFZ
#cV1998 12  1 20 32 34.41036400   32089       CTS   FIT  GFZ
#cV1999  6  8  6 59  4.41155200   33721       CTS   FIT  GFZ
#cV1999 10 16 18 29  9.84710700   32334       CTS   FIT  GFZ
#cV2000  1 12 10 24 59.80990000   10244       CTS   FIT  GFZ
#cV2000  4 20 15 35 32.88763100   12527       CTS   FIT  GFZ
#cV2000  7  8 22 27 12.85165100   14567       CTS   FIT  GFZ
#cV2000  9 26  5 56 38.42128200   16558       CTS   FIT  GFZ
#cV2001  1 13  7 31 47.41130700   19243       CTS   FIT  GFZ
#cV2001  5  2  9 59 52.84461000   21838       CTS   FIT  GFZ
#cV2001  9 18  5  3 35.81895200   25283       CTS   FIT  GFZ
#cV2001 11 26 14 44 31.41142800   27028       CTS   FIT  GFZ
#cV2002  5  4  6 20 49.81133400   30918       CTS   FIT  GFZ
#cV2002 12 18  7 52 34.01130600   36493       CTS   FIT  GFZ
#cV2003  4 26  5 28 33.86726700   10851       CTS   FIT  GFZ

**Comment by remkos** [comment]
This is now resolved. The GFZ SLCCI orbits on passes in the following cycles were updated on the Delft RADS server:
pn: 3, 4, 20, 307
tx: 3, 10, 33, 51, 62, 76, 99, 123, 229, 230, 248, 249, 261, 262, 270, 280, 287, 288, 296, 318, 332, 339, 355, 378, 379, 391
Note: there remain some gaps in the coverage of these orbits. There are simply no orbits available for these periods.
