### ISSUE TITLE
GFZ SLCCI orbit in Nov 2017 update

### ISSUE THREAD

**Issue by samroyston** [remkos/rads#116]
The November 2017 commit should have included the Ver11 GFZ SLCCI orbit product for js1, js2 and other missions; see issue #77. The new field (426) is now included in the *.nc database, but there is no valid data. Checking for js1 for example, the fields are filled with NaNs.

**Comment by remkos** [comment]
I was able reproduce the problem you see. Despite testing on TOPEX and Poseidon data, and error slipped into the rads.xml file, forgetting to create an add_offset of 1300 km for Jason-1 and Jason-2.
TOPEX and Poseidon data were now affected.

**Comment by remkos** [comment]
Reprocessing of the Jason-1 and Jason-2 data is under way. Expect upload over the weekend.

**Comment by remkos** [comment]
All updates were uploaded on Friday 8 December. This impacts Jason-1 (all mission phases) and Jason-2 (Phase A) only.
