### ISSUE TITLE
Consider adding XGM2016 geoid model

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#119]
The XGM2016 geoid model is a precursor for EGM2020.

http://icgem.gfz-potsdam.de/calc

**Comment by remkos** [comment]
geoid_xgm2016 has now been added to CS2 cycles 4-102, thus covering all of the mission.

**Comment by ValZapod** [comment]
Meanwhile XGM2019 and XGM2019e and even XGM2020 are available!

**Comment by remkos** [comment]
We have since abandoned `geoid_xgm2016`
