### ISSUE TITLE
Upgrade SRTM30_PLUS to V11 and/or to SRTM15_PLUS V1

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#120]
SRTM30_PLUS V11 was released in November 2014, shortly after RADS added V10.
A higher resolution field is also available (SRTM15_PLUS, entire grid V1).               

http://topex.ucsd.edu/WWW_html/srtm30_plus.html

**Comment by leuliett** [comment]
I wrote David Sandwell to get a recommendation. His reply was:

> SRTM15_PLUS is in pretty good shape and we don’t plan another version until late this year.  Feel free to use it for anything.  There are some restrictions for commercial users only. 

In the next RADS update, I'd recommend that we replace SRTM30_PLUS with SRTM15_PLUS.

**Comment by remkos** [comment]
OK. I added the variable name already.

**Comment by remkos** [comment]
Reopened, because it will still need to be added to the database everywhere.

**Comment by remkos** [comment]
Now added srtm15 to the alias of topo. See commit 42fda96.

**Comment by remkos** [comment]
SRTM15 has since been updated to version v2.6. This we should pick up as something to add with the new GDR-G standards.

Closed with reference to #199
