### ISSUE TITLE
radsstat --minmax does not number output columns correctly in header

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#121]
Column numbering in the ASCII output header doesn't account for the full range of columns.

For example:
radsstat -Sj3 -Vsla,swh --minmax
prints:
```
# ( 6- 7) mean, stddev, min and max of sea level anomaly [m]
# (10-11) mean, stddev, min and max of Ku-band significant wave height [m] 
```
Instead of:
```
# ( 6- 9) mean, stddev, min and max of sea level anomaly [m]
# (10-13) mean, stddev, min and max of Ku-band significant wave height [m]

```

**Comment by remkos** [comment]
In fact, the output should have been:
<pre>
# ( 4- 7) mean, stddev, min and max of sea level anomaly [m]
# ( 8-11) mean, stddev, min and max of Ku-band significant wave height [m] 
</pre>
Fixed as above.
