### ISSUE TITLE
Installation of initial data directory and data/conf

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#122]
Users report an expectation that "make install" should create the directory specified by --datadir=DIR and move the conf directory into it.

**Comment by remkos** [comment]
This was always the case. In the Makefile in the conf directory, it says:
<pre>
install:	all
	$(INSTALL_DIR) $(bindir) $(datadir)/conf
	$(INSTALL_DATA) *.xml $(datadir)/conf
</pre>
So clearly `$(datadir)` is created, as is the subdirectory `conf`, and the `*.xml` files are put in it.
