### ISSUE TITLE
memory leak in radscolin

### ISSUE THREAD

**Issue by ezaron** [remkos/rads#123]
Symptoms:
Using radscolin across multiple missions and passes leads to a process which appears to use a growing amount of RAM over time (as inferred from output of a command like "htop"). The memory footprint grows at a rate of roughly 1GB/hr on my machine.
radscolin --xml=./rads.xml --sat=tx/a --cycle 4,364 --sat=j1/a --cycle 1,259 --sat=j2/a --cycle 1,303 --sat=j3/a --cycle 1,45 -r 0 -o txaj1aj2aj3a_sla/sla#.nc --var lat,lon,time,sla,swh,swhhp,eta108l,eta108s

Platform information:
(1)  uname -a
Linux baburu 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
(2)  nf-config --all
This netCDF-Fortran 4.4.3 has been built with the following features: 
  --cc        -> gcc
  --cflags    ->  -I/usr/include -Wdate-time -D_FORTIFY_SOURCE=2
  --fc        -> gfortran
  --fflags    -> -I/usr/include
  --flibs     -> -L/usr/lib -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -lnetcdf -lnetcdf 
  --has-f90   -> no
  --has-f03   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --prefix    -> /usr
  --includedir-> /usr/include
  --version   -> netCDF-Fortran 4.4.3
(3) gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
(4) gfortran --version
GNU Fortran (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
(5) config.log says this:
It was created by RADS configure 4.2.11, which was
generated by GNU Autoconf 2.69.  Invocation command line was
  $ ./configure --prefix=/home/ezaron/opt

Other information:
I am using the "<data branch = ..." functionality. I don't know if the bug exists without it.

-Ed

**Comment by remkos** [comment]
Obsolete.
