### ISSUE TITLE
swh and sig0 are all NaN from Sentinel-3a

### ISSUE THREAD

**Issue by aribal2018** [remkos/rads#126]
I think, this is a bug?
Here, what I did:

rads2nc -S 3a -C 2 -P 100 -V time,lat,lon,swh,swh_ku,swh_c,sig0,sig0_ku,sig0_c,wind_speed,range_numval,qual_swh,qual_sig0,surface_type,surface_class,swh_rms,sig0_rms -v

This gives file: 3ap0100c002.nc
When I check the contents of the file, I got the following:

1. ncdump -v swh 3ap0100c002.nc | less 
data:
 swh = _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
which means all are NaN.

2.  ncdump -v swh_ku 3ap0100c002.nc | less
data:
 swh_ku = 5050, 689, 181, 181, 181, 181, 181, 181, 181, 181, 181, 181, 780,
    181, _, 2222, 1195, 181, _, 181, 4111, 2322, _, _, _, _, _, _, _, 1170,
    _, _, _, 5532, _, 1307, 2028, _, 1299, _, _, _, _, 181, 3229, 4895, _, _,
    1005, 181, 181, 4876, 531, 181, _, 683, 6176, _, 6838, _, 3934, _, 3818,
    2244, 181, 4314, 1320, _, 1156, 181, 669, 181, 2613, _, _, 7192, 3248,
    181, _, _, 2777, _, 2889, 1777, _, _, _, _, _, 2182, _, _, 181, 475, 666,
    887, 1456, 1224, 611, _, _, 181, _, _, _, 1059, 1088, _, 2721, 4148,
    1669, 3518, _, 2624, _, 6246, 3611, 1136, _, 1843, 4126, 1837, 2215,
    2896, 2403, 2465, 2495, 3111, 2586, 2564, 5161, 3977, 2651, 3118, 3058,
    2889, 3014, 3054, 3327, 3138, 2906, 3018, 2823, 2861, 2845, 2846, 2999,
    2816, 2762, 2943, 2883, 2953, 3452, 3277, 3015, 3193, 3056, 3498, 3003,
This gives some values which are not NaN.

3.  ncdump -v sig0 3ap0100c002.nc | less
data:
 sig0 = _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
These are also NaN

4.  ncdump -v sig0_ku 3ap0100c002.nc | less
data:
 sig0_ku = _, _, _, _, _, _, 612, 726, 972, 1101, 1164, 1049, 946, 728, 950,
    894, 774, 692, _, 806, 818, 699, _, _, _, _, _, _, _, 1065, 898, 650,
    611, _, _, _, 604, _, 1033, _, 665, _, _, _, 781, 848, _, _, 971, 1037,
    901, 742, 696, 836, _, _, _, _, 728, _, _, _, 809, 783, 798, 600, 639, _,
    _, _, 648, 678, _, _, _, 855, 615, 726, _, _, _, _, 728, 684, _, _, _, _,
    _, 1811, _, _, 1920, 1952, 1948, 2025, 1946, 1863, 1610, _, _, 1594, _,
    _, _, 1550, 1608, _, 1862, 1689, 1843, 1973, 1827, 1795, 1645, 1609,
    1632, 1668, 1892, 1745, 1754, 1494, 1069, 1056, 1051, 1026, 1053, 1042,
    1055, 1135, 1318, 1421, 1264, 1036, 1023, 1027, 1009, 1003, 997, 1008,
    1008, 997, 996, 1000, 997, 991, 992, 979, 981, 980, 988, 977, 968, 980,
    978, 987, 980, 971, 983, 985, 998, 1012, 1008, 1000, 1004, 1012, 998,

5. ncdump -v qual_swh 3ap0100c002.nc | less
data:
 qual_swh = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, _, 0, 0, 0,
    _, _, _, _, _, _, _, 0, 0, 0, 0, 0, _, 0, 0, _, 0, _, 0, 0, 0, 0, 0, 0,
    _, _, 0, 0, 0, 0, 0, 0, _, 0, 0, _, 0, _, 0, _, 0, 0, 0, 0, 0, _, 0, 0,
    0, 0, 0, _, _, 0, 0, 0, _, _, 0, _, 0, 0, _, _, _, _, _, 0, _, _, 0, 0,
    0, 0, 0, 0, 0, _, _, 0, _, _, _, 0, 0, _, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

From these experiments, we can see that only SWH and SIG0 do not have any real number.
I also have checked Pass 442 and I found similar results.

Thank you very much.
best regards,
Agustinus

**Comment by remkos** [comment]
Sorry for the late response.
The issue is that **both** `swh` and `swh_ku` as well as both `sig0` and `sig0_ku` appear on the command line. These are in fact pairs of the same field. Somehow (to be analysed) rads2nc then only properly handles one of the pair, `swh_ku` and `sig0_ku`.
So removing the "duplicate" `swh` and `sig0` should solve this.

Nonetheless, I keep this open since it is clearly to be considered a bug, though not with a high priority.

**Comment by remkos** [comment]
Fixed with commit 3044952
