### ISSUE TITLE
undefined reference to nf90_def_var_deflate_

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#136]
-----rads-lr-bounces@lists.tudelft.nl wrote: -----
To: rads-lr@lists.tudelft.nl
From: Michiel.Otten@esa.int
Sent by: rads-lr-bounces@lists.tudelft.nl
Date: 08/30/2018 03:39PM
Subject: [Rads-lr] installing latest version of rads4

Dear all, 
I am getting the following error message at compilation stage of rads4: 

motten@navdev1:/home/motten/linux/rads> make 
make  -C src 
make[1]: Entering directory '/home/motten/linux/rads/src' 
ifort  -Iinclude -I. -I/home/motten/linux/netcdf-4.0/include  -c -o rads_misc.o rads_misc.f90 
ifort  -Iinclude -I. -I/home/motten/linux/netcdf-4.0/include  -c -o rads_math.o rads_math.f90 
ifort  -Iinclude -I. -I/home/motten/linux/netcdf-4.0/include  -c -o rads_netcdf.o rads_netcdf.f90 
printf "character(len=rads_naml), parameter :: radsdataroot = '%s'\n" /mnt/gndata/motten/rads > config.f90 
printf "logical, parameter :: little_endian = .%s.\n" true >> config.f90 
printf "character(len=rads_varl), parameter :: rads_version_id = '%s'\n" 4.3.0 >> config.f90 
ifort  -Iinclude -I. -I/home/motten/linux/netcdf-4.0/include  -c -o rads.o rads.f90 
ifort  -Iinclude -I. -I/home/motten/linux/netcdf-4.0/include  -c -o rads3.o rads3.f90 
ar rv librads.a rads_time.o rads_misc.o rads_grid.o rads_geo.o rads_math.o rads_netcdf.o xmlparse.o rads.o rads3.o 
r - rads_time.o 
r - rads_misc.o 
r - rads_grid.o 
r - rads_geo.o 
r - rads_math.o 
r - rads_netcdf.o 
r - xmlparse.o 
r - rads.o 
r - rads3.o 
ranlib librads.a 
ifort  -Iinclude -I. -I/home/motten/linux/netcdf-4.0/include   rads2asc.f90 librads.a  -L/home/motten/linux/netcdf-4.0/lib -lnetcdf -o rads2asc 
librads.a(rads_netcdf.o): In function `rads_netcdf_mp_nf90_def_axis_': 
rads_netcdf.f90:(.text+0x563): undefined reference to `nf90_def_var_deflate_' 
../config.mk:83: recipe for target 'rads2asc' failed 
make[1]: *** [rads2asc] Error 1 
make[1]: Leaving directory '/home/motten/linux/rads/src' 
Makefile:43: recipe for target 'src' failed 
make: *** [src] Error 2 

I succesfully installed netcdf-4.0 and all test ran ok (make check), I had an older version of rads4 installed which did compile but gave me a run time crash (which I assume is due to the fact that my datafiles I downloaded are newer). So I pulled the latest version from git and experienced the above error at compilation. 

Thanks in advance for any help, 
Michiel. 

PosiTim for ESA - European Space Agency

Michiel Otten
Navigation Engineer
Navigation Support Office, OPS-GN

ESOC
Robert-Bosch-Str. 5
64293 Darmstadt, Germany
Michiel.Otten@esa.int | navigation-office.esa.int
T +49 6151 90 2029

minor update:

If I revert in git to the previous commit (cb71c4cf6f3c) all works fine. So the bug is in rads_netcdf.f90 which was updated on the 21st of August. Did not have time yet to check what goes wrong in the code. But be aware that if you update to the latest version of the master you may run into compile problems.

Cheers,
Michiel.

Michiel Otten
Navigation Support Office, OPS-GN
European Space Operations Centre ESOC
Robert Bosch Strasse 5
64293 Darmstadt - Germany
phone: +49.6151.90.2523 fax: +49.6151.90.2271
http://navigation-office.esa.int

**Comment by remkos** [comment]
This is not, in fact, a bug. But the fact that you use netcdf-4.0. Please note that RADS4 requires a somewhat newer version of NetCDF 4. 4.0 is from 2010! Try at least netCDF 4.4.

But ... nf90_def_var_deflate is actually not used at this moment, only added for future use.
So I could introduce some switch to check to netCDF version.

I rather force a newer version of netCDF. I'll build in some check for that and write it in the documentation.

**Comment by remkos** [comment]
This is now addressed by commit f9a5f4e.
Your can find this also in release tag v4.3.1 (https://github.com/remkos/rads/releases/tag/v4.3.1)
Considered bug fixed and closed.

**Comment by Ted-del** [comment]
Remkos,

I met the similar question (Macbook pro , macOS Sierra  10.12.6).
Any suggestions?

Thanks.


./configure
configure: RADS, version 4.3.6
checking build system type... x86_64-apple-darwin16.7.0
checking host system type... x86_64-apple-darwin16.7.0
checking target system type... x86_64-apple-darwin16.7.0
configure: checking user options
checking whether debugging is desired... no
checking whether developer tools are desired... no
checking for nf-config... /usr/local/bin/nf-config
checking for Fortran 90 compiler... gfortran
configure: finding Fortran 90 compiler
checking whether the Fortran compiler works... yes
checking for Fortran compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... (cached) no
configure: setting up Fortran 90
checking for Fortran flag to compile .f90 files... none
checking for Fortran flag needed to accept free-form source... none
checking for Fortran flag needed to accept 132 column source lines... none
checking Fortran 90 module inclusion flag... -I
checking how to get verbose linking output from gfortran... -v
checking for Fortran libraries of gfortran...  -L/usr/local/lib -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0/../../.. -lgfortran -lquadmath -lm
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... (cached) no
checking for gcc option to accept ISO C89... none needed
checking for dummy main to link with Fortran libraries... none
checking for Fortran name-mangling scheme... lower case, underscore, no extra underscore
checking if gfortran can handle Fortran 90... yes
checking for additional compiler flags (for developers)... 
checking for NetCDF includes... -I/usr/local/include
checking for NetCDF libraries... -L/usr/local/lib -lnetcdff -L/usr/local/lib -lnetcdf -lnetcdf
checking if gfortran can compile a simple NetCDF program... yes
Succeeded to compile Fortran 90 code with NetCDF version 4.7.4 of May 12 2020 18:51:14 $                                                 
checking for lapack options (for developers)... 
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
configure: finding other utilities
checking whether ln -s works... yes
checking for ranlib... ranlib
checking for a BSD-compatible install... /usr/bin/install -c
configure: creating ./config.status
config.status: creating config.mk
config.status: creating src/rads-config
config.status: creating doc/manuals/rads_config.tex

make
/Library/Developer/CommandLineTools/usr/bin/make  -C src 
printf "character(len=rads_naml), parameter :: radsdataroot = '%s'\n" /Volumes/datacol/rads-4.3.6/share > config.f90
printf "logical, parameter :: little_endian = .%s.\n" true >> config.f90
printf "character(len=rads_varl), parameter :: rads_version_id = '%s'\n" 4.3.6 >> config.f90
gfortran -O2  -Iinclude -I. -I/usr/local/include  -c -o rads.o rads.f90
gfortran -O2  -Iinclude -I. -I/usr/local/include  -c -o rads3.o rads3.f90
ar rv librads.a rads_time.o rads_misc.o rads_grid.o rads_geo.o rads_math.o rads_netcdf.o xmlparse.o rads.o rads3.o 
r - rads_time.o
r - rads_misc.o
r - rads_grid.o
r - rads_geo.o
r - rads_math.o
r - rads_netcdf.o
r - xmlparse.o
r - rads.o
r - rads3.o
ranlib librads.a
gfortran -O2  -Iinclude -I. -I/usr/local/include -L/usr/local/lib  rads2asc.f90 librads.a  -L/usr/local/lib -lnetcdff -L/usr/local/lib -lnetcdf -lnetcdf -o rads2asc
Undefined symbols for architecture x86_64:
  "_nf90_def_var_deflate_", referenced from:
      ___rads_netcdf_MOD_nf90_def_axis in librads.a(rads_netcdf.o)
ld: symbol(s) not found for architecture x86_64

-------This netCDF 4.7.4 has been built with the following features: 

  --cc            -> gcc
  --cflags        -> -I/usr/local/include -I/usr/local/netcdf-fortran-4.4.4/include
  --libs          -> -L/usr/local/lib -lnetcdf
  --static        -> -lm -lz -lcurl 

  --has-c++       -> no
  --cxx           -> 

  --has-c++4      -> no
  --cxx4          -> 

  --has-fortran   -> yes
  --fc            -> gfortran
  --fflags        -> -I/usr/local/include
  --flibs         -> -L/usr/local/lib -lnetcdff -L/usr/local/lib -lnetcdf -lnetcdf
  --has-f90       -> no
  --has-f03       -> yes

  --has-dap       -> yes
  --has-dap2      -> yes
  --has-dap4      -> no
  --has-nc2       -> yes
  --has-nc4       -> no
  --has-hdf5      -> no
  --has-hdf4      -> no
  --has-logging   -> no
  --has-pnetcdf   -> no
  --has-szlib     -> no
  --has-cdf5      -> yes
  --has-parallel4 -> no
  --has-parallel  -> no

  --prefix        -> /usr/local
  --includedir    -> /usr/local/include
  --libdir        -> /usr/local/lib
  --version       -> netCDF 4.7.4
