### ISSUE TITLE
Consider adding MSS DTU18

### ISSUE THREAD

**Issue by remkos** [remkos/rads#137]
The model is already defined in `rads.xml` by commit 3d290d7

**Comment by remkos** [comment]
MSS DTU18 was added to products by operational processing by commit 7f14477 on 1 Nov 2018

**Comment by remkos** [comment]
Status 21 Feb 2019, 09:24 UTC:
All S3A and S3B data now contain MSS DTU18

**Comment by remkos** [comment]
Status 21 Feb 2019, 09:52 UTC:
Also all CS2 data now contain MSS DTU18

**Comment by remkos** [comment]
Status 21 Feb 2019, 10:14 UTC:
Also all JA3 data now contain MSS DTU18

**Comment by remkos** [comment]
Status 21 Feb 2019, 12:51 UTC:
Also all SRL and JA2 data now contain MSS DTU18

**Comment by CarstenLudwigsen** [comment]
Can you update for N1, E1 and E2 with MSS DTU18 as well?

**Comment by remkos** [comment]
With this update, mss_dtu13 can disappear. See commit ba91072

**Comment by remkos** [comment]
We are now removing `mss_dtu18` as per #201
