### ISSUE TITLE
could not find any data for variable "geoid_xgm2016"

### ISSUE THREAD

**Issue by j08lue** [remkos/rads#147]
For a data extraction with CryoSat-2, we would like to use the improved geoid `geoid_xgm2016` and can see it is defined in the `rads.xml` (as per #119). But when we request it from a recently synced RADS database, we get the message 

```
could not find any data for variable "geoid_xgm2016"
```

Is this expected or are we missing something?

**Comment by remkos** [comment]
Dear @j08lue . I'm afraid this is expected, as this geoid was only added to the processing since March 2018. So all data created after that should have it.

Meanwhile, I'll go and add this geoid at least to the CryoSat-2 data to help you out.

**Comment by remkos** [comment]
I can confirm that the c2 data from cycle 103 onwards already contains geoid_xgm2016.

**Comment by remkos** [comment]
geoid_xgm2016 has now been added to CS2 cycles 4-102, thus covering all of the mission.

**Comment by j08lue** [comment]
Excellent, thanks. I can see it is just another variable in the source netCDF files. 

I would actually like to use that geoid for many other missions. Is there any chance you could add it to the others, too?

I also propose an alternative to adding the geoid to all time steps: #148
