### ISSUE TITLE
Make geoids static data sources

### ISSUE THREAD

**Issue by j08lue** [remkos/rads#148]
I can see geoid values are contained in the database for each time step. When a new, improved geoid is added, you would have to back-port it to all data for people to be able to use it consistently throughout time series.

Maybe the geoids could instead be static data sources in the database, rather than added to every time step, and then the `rads` software could extract them on the fly as needed. That way, new geoids are immediately available to all missions and all times. What do you think?

**Comment by remkos** [comment]
In fact, that is already possible :)
RADS can interpolate any NetCDF grid that conforms to the CF-conventions on the fly.

Here is an example:
```
<var name="my_geoid">
    <units>m</units>
    <data source="grid">my_geoid.nc</data>
</var>
```
See more about this in Section 4.3.3 of the [RADS User Manual](https://github.com/remkos/rads/blob/master/doc/manuals/rads4_user_manual.pdf)
Here you will discover that this can also be done for interpolating in other dimensions than longitude and latitude.

**Comment by j08lue** [comment]
Great, thanks. I'll consider using this as a workaround for #147 then.
