### ISSUE TITLE
libraries to build devel code?

### ISSUE THREAD

**Issue by andreustaylor** [remkos/rads#151]
# cant find full code to build devel code

Advise appreciated.

I am investigating options to build resilience into our RADS-based obs processing.
 - interest in replicating some processing of raw data sources   
 - only care about near-real-time data
-  for instance, to create a local backup subset of the database using IDGRs etc  

## Apparently missing libraries
A face-value the following paths related to ALTIM aren't on this repo
- https://github.com/remkos/rads/blob/ab0ae17ce09861ac8bea407c942c61a3f60f3d85/devel/Makefile#L36

- https://github.com/remkos/rads/blob/ab0ae17ce09861ac8bea407c942c61a3f60f3d85/configure#L4305

**Comment by remkos** [comment]
The developer tools are only for the developers that build the data base.
So please configure without the `--devel` flag, and you will be all set.
