### ISSUE TITLE
How to download the NIC09 Model?

### ISSUE THREAD

**Issue by 1acheng** [remkos/rads#157]
like `nic09_clim.nc`  and `nic09_gtec.nc` 

Is the nic09 model still public access?

Thanks.

**Comment by leuliett** [comment]
They are available at:
ftp://ftp.star.nesdis.noaa.gov/pub/sod/lsa/rads/nic09
Eric
______________________________________________________________
Eric W. Leuliette, PhD (he/him/his)         work: 301.683.3380
Branch Chief                                fax:  301.683.3301
Laboratory for Satellite Altimetry          room: 3237
NOAA Jason-3/Sentinel-6 Program and Project Scientist
National Oceanic and Atmospheric Administration
NOAA Center for Weather and Climate Prediction (NCWCP)
5830 University Research Court, E/RA3
College Park MD 20740-3818             Eric.Leuliette@noaa.gov
______________________________________________________________

The contents of this message are mine personally and do not necessarily reflect any position of NOAA.

**Comment by 1acheng** [comment]
Thanks.
