### ISSUE TITLE
Why do we need ionopheric climate model?

### ISSUE THREAD

**Issue by 1acheng** [remkos/rads#158]
We have better GIM, like JPLG.

Why do we need ionopheric climate model? like nic09 model.

What role does the ionospheric correction play?  I couldn't imagine that the GIM or nic09 model can help the altimetric distances to achieve an accuracy of millimeters. I think both GIM and nic09 model have not so high precision.

In addition, the ionospheric delay can't be eliminated by the dual-frequency (C and Ku) measurements?

Thanks.

**Comment by leuliett** [comment]
For legacy altimeter missions which used only single-frequency altimeters, an ionosphere model is necessary to estimate the path delay.

See the reference: Scharroo, R., Smith, W. (2010). A global positioning system-based climatology for the total electron content in the ionosphere Journal of Geophysical Research: Space Physics 115(A10), n/a-n/a. https://dx.doi.org/10.1029/2009ja014719 <https://dx.doi.org/10.1029/2009ja014719>

"The creation of the NOAA Ionosphere Climatology 2009 (NIC09) was driven by the need for accurate ionospheric path delay information for single‐frequency altimeters prior to the broad availability of GPS dual‐frequency data. Those earlier altimeter missions of the single‐frequency era, Geosat (1985–1989), ERS‐1 (1991–1996), Poseidon (1992–2002), and ERS‐2 (launched 1995), are highly important for the construction of the long‐term climate record of sea level change."

The ESA Climate Change Initiative compared ionospheric models and their impact on the climate record. For example,
https://www.esa-sealevel-cci.org/webfm_send/162

Eric

**Comment by 1acheng** [comment]
@leuliett  

Thanks for your perfect answer.

**Comment by 1acheng** [comment]
@leuliett 

one more question.

Now that there are dual-frequency observations, is the ionospheric delay eliminated by dual-frequency combination of observations? Or, it is corrected by models or JPL GIM?

Thanks.

**Comment by leuliett** [comment]
Section 3.6 of the data manual documents how the ionospheric delay is used for each mission.
For the dual-band altimeters (j1, j2, j3, n1, tx, 3a, 3b), the default iono correction is
1) the along-track smoothed delay computed from Ku/C bands, or
2) GIM where the dual-band value isn’t valid, or
3) NIC09 where GIM and the dual-band aren’t valid.

For Cryosat-2, ERA-2, Geosat-FO, and AltiKa, the default iono correction is:
1) GIM, or
2) NIC09 where GIM isn't valid.

For ERS-1, Geosat, and Posideon-1, the default iono correction is:
NIC09
