### ISSUE TITLE
c2 time attributes are in TAI

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#166]
The first_meas_time and last_meas_time attributes for c2 are copied directly from the ESA CryoSat-2 Ocean Processor products. In the original products, they are provided in TAI. They will need to be converted to UTC to be consistent with the other missions.

**Comment by BernardVas** [comment]
Also, I think that there is an issue in the equator_time. This time is not in the range first_meas_time - last_meas_time. Right?

**Comment by remkos** [comment]
@leuliett : Can we close this?

**Comment by leuliett** [comment]
Closed with commit a5418429d76d93e6787cb7e8ff2acb044c44d65f
