### ISSUE TITLE
URL for new user registration is missing in the User Manual

### ISSUE THREAD

**Issue by sanAkel** [remkos/rads#168]
Hi All,
I am just getting started with [RADS](https://github.com/remkos/rads).

Chapter 3, pp.7 of the [RADS User Manual](https://github.com/remkos/rads/raw/master/doc/manuals/rads4_user_manual.pdf) says
>At the beginning rsync will ask you to enter the password for radsuser. It will have been provided to you when you registered as a user.

I am not sure what is the ⬆️ **URL for registering as a user**. Appreciate if someone could please provide it here and/or https://github.com/remkos/rads/blob/0dc9ef2bd2c362662f9e0fe60e6927bb7d7fc873/doc/manuals/rads4_user_manual.tex#L250
Thank you!

**Comment by sanAkel** [comment]
Thanks to [Marc Naeije](https://www.tudelft.nl/staff/m.c.naeije), for providing the solution (_password_ hint). There is no registration, hence closing this issue.

**Comment by yadidya-b** [comment]
Can you please explain what the solution is?

**Comment by sanAkel** [comment]
@yadidya-b I don't think its wise on my part to type it here. So you will have to decipher from the following.

- Concatenate following `strings` to figure out the password.
- `strings` are abbreviations of following altimeter missions from table 3.1 of [manual](https://github.com/remkos/rads/blob/master/doc/manuals/rads4_user_manual.pdf).
- Altimeter missions are: `ERS-2`, `GFO`, `Jason-1`, `Envisat`.

**Comment by yadidya-b** [comment]
Thank you @sanAkel!
