### ISSUE TITLE
Reinstate EIGEN6 geoid

### ISSUE THREAD

**Issue by remkos** [remkos/rads#172]
The EIGEN6 geoid was removed in July 2021 with commit 0e79390
Upon popular request, it should be reinstated, i.e. included back in rads_add_common and in the data that was since produced.

**Comment by leuliett** [comment]
I propose that we drop support of geoid_xgm2016.

**Comment by remkos** [comment]
Updated on:
- SRL
- CS2
- S3A, S3B
- S6A
- JA3
(Status 21 Feb '22)

**Comment by remkos** [comment]
This can be closed, since all missions now have geoid_eigen6
