### ISSUE TITLE
Bug in Jason-3 ellipsoid transformation

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#175]
The transformation of Jason-3 GDR-F from WGS84 to the TOPEX ellipsoid has an error: longitude is passed to dhellips instead of latitude. A suggested fix is in the branch https://github.com/remkos/rads/tree/WGS84. Jason-3 will need to be reprocessed to implement it.

**Comment by remkos** [comment]
@leuliett : commit fd55d05 in the WGS84 branch was not entirely correct, as the "lat" variable does not exist.
The commit 01eb11e does this correctly for rads_gen_jason_gdrf. No change is needed for rads_gen_s3.

**Comment by remkos** [comment]
Note that Jason-3 data will need to be reprocessed from the start to fix this properly throughout the data.

**Comment by remkos** [comment]
All Jason-3 data has been reprocessed and uploaded by 2022-02-10 13:00 UTC.

Also note: this bug was not present in rads_gen_s3.f90 nor in rads_gen_s6.f90
