### ISSUE TITLE
Update pole tide to latest IERS conventions

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#176]
Update the pole tide solution to S. Desai pole tide with new IERS linear mean pole.

1) The secular pole computation in poletide.f90 needs to be updated:
        ! Remove GIA contribution to polar motion (Desai, 2015)
        poletab(i)%xpole = x - (0.05097d0 + 0.00062d0 * t)
        poletab(i)%ypole = y - (0.33449d0 + 0.00348d0 * t)

GDR-F is using IERS Conventions (2010) v1.3.0, Chapter 7.1.4:
The coordinates of that secular pole designated (xs, ys) and are given in milliarcseconds by
xs = 55.0+1.677∗(t−2000), ys = 320.5+3.460∗(t−2000), where t is the date in years of 365.25 days.

References:
IERS Conventions (2010) v1.3.0, Chapter 6 and 7:
https://iers-conventions.obspm.fr/conventions_versions.php#official_target

Desai, S., Wahr, J., Beckley, B., 2015, “Revisiting the pole tide for and from satellite altimetry,“
J. Geod., 89, 1233-1243, doi:10.1007/s00190-015-0848-7.

2) A more complete implementation of the pole tide would include more harmonics than the degree-2 values in poletide.f90
Approximately 90% of the variance of the ocean pole tide potential is provided by the degree n = 2 spherical harmonic components, with the next largest contributions provided by the degree n = 1 and n = 3 components, respectively (see Figure 6.1). Expansion to spherical harmonic degree n = 10 provides approximately 99% of the variance. However, adequate representation of the continental boundaries will require a spherical harmonic expansion to high degree and order.

The full set of coefficients is available at: ftp://tai.bipm.org/iers/conv2010/chapter6/desaiscopolecoef.txt

**Comment by remkos** [comment]
I will use the same implementation as in Sentinel-6 and Jason-3 GDR-F. The coefficients you refer to are there expanded into 2D grids. A file poletide_aux.nc has already been put in $RADSROOT/altim/data for that purpose.

**Comment by remkos** [comment]
With commit ad3b7ef the issue is fixed in code.

Will still need to be applied to all RADS data.

**Comment by remkos** [comment]
The following mission data have been fully updated with the pole tide fix:
- JA3 (10 Feb '22)
- S6A - all flavours (11 Feb '22)
- SRL (12 Feb '22)
- S3A and S3B - NTC (17 Feb '22) - STC since 26 Jan '22 (21 Feb '22)
- CS2 (21 Feb '22)
- JA2 (6 Apr '22)
- TPX (as part of the update to GDR-F, Feb '24)
- JA1 (10 Apr '24)

**Comment by remkos** [comment]
Closing this in favour of #204
