### ISSUE TITLE
Add S6 manoeuvre_flag

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#177]
Particularly for the NRT data, it would be helpful to NOAA users if the manoeuvre_flag was included in S6.

**Comment by remkos** [comment]
- From this I understand you are not advocating to put it on the data retroactively. Correct?
- Do you have a recommendation as for the variable name to use in RADS?

**Comment by remkos** [comment]
Should be implemented by commit 5e7710c.
Back to @leuliett to verify and close.
