### ISSUE TITLE
Update reference frame offset for S6A once reprocessing have been completed

### ISSUE THREAD

**Issue by remkos** [remkos/rads#180]
Reprocessing (all but) completed on 24 May '22. Now the reference frame offset can be properly calculated.

**Comment by andreustaylor** [comment]
Thanks for the update.
I am interested to keep up with the timing of when the new S6A offset will appear in the database, as it is a factor in how we configure an application.

**Comment by remkos** [comment]
The variables ref_frame_offset, ref_frame_offset_mle3 and ref_frame_offset_nr are now set to their appropriate values, for 6a.lr as well as 6a.hr.
See commit a948a7fc.

Note that values for j3 have been (slightly) updated as well. Old and new values given below (in mm).

  | JA3 old | JA3 new | S6A old | S6A Side A | S6A Side B
-- | -- | -- | -- | -- | --
LR MLE4 | -23.0 | -22.6 | 0.0 | -13.2 | -11.9
LR MLE3 | -9.0 | -8.9 | 0.0 | -17.5 | -15.8
LR adaptive/NR | -48.0 | -47.7 | 0.0 | -19.6 | -17.2
HR |   |   | 0.0 | -23.5 | -21.5
