### ISSUE TITLE
rads_pre_sort_passes occasionally fails for 3a/3b pass 770

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#181]
rads_pre_sort_passes occasionally fails to recognize the change to a new cycle and continues to include passes into a S3?_SR_2_WAT___0??_770______MAR_O_NR_004.nc.

When rads_gen_s3 reads this file, it produces a " Error: file skipped: too many measurements" that halts the NRT updates.

**Comment by remkos** [comment]
Do you have a specific example that I could duplicate?
I do not see any of this happening on my side.

**Comment by remkos** [comment]
Please check if commit 1667e83 worked.

**Comment by remkos** [comment]
This appears to be related to `make_orf` rather than `rads_pre_sort_passes`. The ORF files seems to stop at the end of the current cycle, until MOE data is available for the next cycle. This should not happen.

**Comment by remkos** [comment]
With the update of `make_orf` and setting an upper time limit 14 days into the future via `--ymd` in the scripts that call `make_orf`, this issue is resolved.
