### ISSUE TITLE
3a mean step change 

### ISSUE THREAD

**Issue by andreustaylor** [remkos/rads#184]
A step change is apparent in 3a SLA when processing with default tools.
This results in recent 3a data appearing to be offset downwards by ~2cm from other satellites.

Can users change configuration in xml to ensure 3a offset remains consistent?

Replication:
radsstat --ymd 20210628,20210701 -l -V sla -S 3a     --> ~0.06 
radsstat --ymd 20220628,20220728 -l -V sla -S 3a   --> ~0.04

**Comment by leuliett** [comment]
The bias change occurs when S3A switches to baseline processor 05 on June 11 starting with cycle 86 and pass 396.

**Comment by leuliett** [comment]
No documentation available from EUMETSAT or Copernicus about the baseline changes.
https://www.eumetsat.int/current-altimetry-processing-baselines
https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-3-altimetry/processing-baseline

**Comment by remkos** [comment]
This has been repaired since the latest full mission reprocessing. See https://www.eumetsat.int/release-sentinel-3-altimetry-marine-bc005-reprocessed-dataset
