### ISSUE TITLE
Mission phase and cycles incorrect with radsstat call

### ISSUE THREAD

**Issue by dstrossman** [remkos/rads#188]
There are two phases of two different missions that I've come across that result in incorrect phase letters:
<pre>
1) $ radsstat -c -Sj2/c
# Statistics of RADS variables (box weight)
# Created: 2023-04-18 15:26:05 UTC: radsstat -c -Sj2/c
#
# Satellite : j2/d
# Cycles    :  332 -  355
# Passes    :    1 -  434
</pre>
<pre>
2) $ radsstat -c -Ssa/a
# Statistics of RADS variables (box weight)
# Created: 2023-04-18 15:26:52 UTC: radsstat -c -Ssa/a
#
# Satellite : sa/b
# Cycles    :    0 -   35
# Passes    :    1 - 1002
</pre>
With the latter call, if you try to narrow down the time range with the following statement, you even get the cycle numbers out of order:

<pre>
$ radsstat -c -Ssa/b --ymd=20150501,20150731
# Statistics of RADS variables (box weight)
# Created: 2023-04-18 14:53:13 UTC: radsstat -c -Ssa/b --ymd=20150501,20150731
#
# Satellite : sa/a
# Cycles    :   36 -   25
# Passes    :    1 - 1002
</pre>

**Comment by leuliett** [comment]
The simplest way to handle examples 1) and 2) would be to shorten the satellite to the 2-letter code. For example 3, the date range doesn't overlap with the selected phase. We would need to add an error message when S(1)%cycles(2) is less than S(1)%cycles(1).

**Comment by remkos** [comment]
I consider example 3 user error, so I'm going to ignore that.
