### ISSUE TITLE
Errors in data source for mode flags: parsing of elseif/elseif/else fails for XML files

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#197]
Richard Ray reported an error for flag_alt_oper_mode: The data source for flag_alt_oper_mode returns "0" regardless of the mission. A similar error occurs for qual_alt_rain_ice.

In rads.f90 incorrectly applies a "pass" to an "else" tag when the previous two tags are "elseif"

One possible workaround would be to change `<else>` to `<else sat="!6a c2 tx pn">` in rads.xml.

```
	<data>flag_alt_oper_mode</data>
	<if sat="6a">
		<flag_values>LRM RAW RMC</flag_values>
		<plot_range>0 2</plot_range>
	</if>
	<elseif sat="c2">
		<flag_values>LRM SAR SARIN</flag_values>
		<plot_range>0 2</plot_range>
	</elseif>
	<elseif sat="tx pn">
		<flag_values>side_A side_B POS</flag_values>
		<plot_range>0 2</plot_range>
	</elseif>
	**<else>**
		<data source="flags">0</data>
	</else>

```

**Comment by remkos** [comment]
This fix is part of release v4.6.3 (https://github.com/remkos/rads/releases/tag/v4.6.3)
