### ISSUE TITLE
SWOT data missing for latitudes less than -56.5-degrees

### ISSUE THREAD

**Issue by AlexaPutnam** [remkos/rads#198]
I ran rads2grd4 for SWOT (cycles 301-315) and found that there were no measurements for bins less than -56.5-degrees latitude. I then compared rads/tracks/sw/b/c313/swp0567c313.nc to the same pass downloaded directly from EarthData, and while the EarthData file did contain measurements  less than -56.5 the RADs file did not.

Here is an example of the command that I'm running:
rads2grd4 --sat sw -V lat,lon,sla,time --min 2 --res 1 -C 313 -o grids4trend/sw_grids1_c313.nc

**Comment by leuliett** [comment]
The offset for alt_gdrf and range_ku for SWOT in the Science orbit is too low (700km) to store the values when they exceed int4 and they are set to NaN. The <compress> field for sw/b will need to be changed and sw/b reprocessed.

**Comment by remkos** [comment]
- rads.xml has been updated.
- reprocessing for the Science Phase has started.

**Comment by remkos** [comment]
Reprocessing of Cycles 314-317 (IGDR and OGDR) completed.
Reprocessing of Cycles 301-313 (GDR) running. Should be finished later today (27 June).

**Comment by remkos** [comment]
Reprocessing of Cycles 301-313 (GDR) completed.
All data has been synced to the RADS server.
