### ISSUE TITLE
Adjust rads_fix_c2 for Baseline C

### ISSUE THREAD

**Issue by GoogleCodeExporter** [remkos/rads#61]
```
In preparation for CryoSat-2 Baseline C, need to update rads_fix_c2 to properly 
deal with sigma0 bias and drift.
i.e.:
1) Apply proper AGC corrections from Baseline C L1A and L1B during retracking.
2) Reanalyse the consequential new sigma0 bias
3) Implement that in rads_fix_c2
```

Original issue reported on code.google.com by `re...@altimetrics.com` on 18 Mar 2015 at 11:23

**Comment by remkos** [comment]
1) Captured in retracking code
2) Analysed: no jump on 1 April
3) Implemented in tag v4.0.1
But still need to look at sigma0 biases

Meanwhile, range bias is properly dealt with in tag v4.0.1 as well.
