### ISSUE TITLE
Installation may require libsz

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#62]
The installation instructions may need to note that szip/libsz may need to be installed.

**Comment by remkos** [comment]
I suppose this would be because of HDF5, which is likely required by netCDF.
But wouldn't that be automatic? If netCDF is installed than HDF5 and szip are needed.
So that should be part of HDF5 install notes.

**Comment by remkos** [comment]
Reference to dependencies of netCDF library has been added to the user manual.
