### ISSUE TITLE
radsxogen: time interval option fails

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#67]
The --dt option no longer works:
radsxogen -Sj2 --dt 2 -C1,10 -Vsla test.nc

radsxogen (v4.1.0-6-gadc5286)
radsxogen: Option "--dt 2" could not be parsed
radsxogen: Use "radsxogen --help" for more info

**Comment by remkos** [comment]
Verified that this indeed fails. The same happens with --dt=2, while --dt2 correctly says: "unknown option".

**Comment by remkos** [comment]
Fixed in 73991c9
