### ISSUE TITLE
radscolin: for --diff, mask should inherit from both half of tracks

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#69]
For radscolin --diff -r0, add mask(j,:) = mask(j,:) .or. mask(j+ntrx,:) in order for the mask to inherit the flags from incoming data from both half of tracks used to create differences:

! If requested, do difference of first half and second half of tracks  
if (out_diff) then
        ntrx = ntrx / 2
        do j = 1,ntrx
                data(j,:,:) = data(j,:,:) - data(j+ntrx,:,:)
                mask(j,:) = mask(j,:) .or. mask(j+ntrx,:)
        enddo
        do j = 2*ntrx,ntrx+1,-1
                info(j+2) = info(j)
        enddo
endif

**Comment by remkos** [comment]
Your suggestion is a good one. Please go ahead and implement it.

**Comment by leuliett** [comment]
Fixed in 1834e64.
