### ISSUE TITLE
rads2grd cell-oriented boundaries doesn't produce expected lon/lat

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#70]
rads2grd -c -Sj2 -C245 -otest.nc
Produces:
 lon = -179.001388888889, -178.004166666667, -177.006944444444, 
    -176.009722222222, -175.0125, -174.015277777778, -173.018055555556, 
    -172.020833333333, -171.023611111111, -170.026388888889, 
    -169.029166666667, -168.031944444444, -167.034722222222, -166.0375, 
    -165.040277777778, -164.043055555556, -163.045833333333, 
    -162.048611111111, -161.051388888889, -160.054166666667, 

 lat = -89.0027777777778, -88.0083333333333, -87.0138888888889, 
    -86.0194444444444, -85.025, -84.0305555555556, -83.0361111111111, 
    -82.0416666666667, -81.0472222222222, -80.0527777777778, 
    -79.0583333333333, -78.0638888888889, -77.0694444444444, -76.075, 
    -75.0805555555555, -74.0861111111111, -73.0916666666667, 

Instead of lon=-179.5,-178.5,...
lat = -89.5, -88.5,...

**Comment by remkos** [comment]
I could duplicate the bug. Should be easy to find.

**Comment by remkos** [comment]
Closed. Fixed in 24babd5.

**Comment by remkos** [comment]
Fixed :)
