### ISSUE TITLE
Allow additional directory tree

### ISSUE THREAD

**Issue by remkos** [remkos/rads#76]
In order to support the ability for users to create alternative data fields without messing with the original RADS data, it would be worthwhile to provide the opportunity to specify an alternative directory tree for such data sets. For example: `<dir>$HOME/radsdata</dir>` as part of a `<var>` block.
Maybe it is worthwhile to then to allow to specify e.g. `<dir>$RADSDATA</dir>` outside `<var>` blocks to be the default.

**Comment by ezaron** [comment]
Hi Remko,
I was studying the rads4 code, and it looks like making the proposed change would be somewhat less trivial that I thought when we discussed it. It looks like the rads_pass type is really the fundamental data structure, which is separate from the rads_var information defined within the rads_sat structure. Combining variables from different pass files would mean carrying two different rads_pass structures and attaching these to the rads_var structure somehow. Then there would be some messy logic under rads_get_var_common to open and read the extra pass file when a variable can't be found in the standard pass file.

I think an easier solution might be to create a new set of "aggregated" pass files using NcML. Within each of these there would be pointers to the native rads pass file and a pointer to the pseudo pass file which only contains the new variables. This would keep rads the same and permit defining new variables within the rads.xml structure exactly as normal. Then, the RADSDATAROOT would simply point to the new directory tree with the hierarchy of NcML files arranged in the rads way.

I'm not sure how much progress I'll make this weekend, but I let you know if I can make this approach work.

-Ed

**Comment by remkos** [comment]
Hi Ed,

Indeed, I came to a similar conclusion that it may be a bit more convoluted than I originally thought. But there must be a way to do this easily.

Indeed, at the moment rads_pass would hold only one filename. But I think it can be made such that it holds only a relative filename. Then the path ahead of the relative filename could be changed depending whether the standard directory tree or an additional directory tree needs to be queried. The directory tree could depend on a directory name to be inserted inside the rads_var structure of a potential alternative variable.

I'll look also into your suggestion of using ncML files. That looks really neat! The only problem, I believe, would be that the file names in those ncML files need to be relative to something. I'll have to see how that can work in a generalised way.

Maybe something like this will work:

Files:
$RADSDATAROOT/sa/a/c001/sap0001c001.nc - The standard netCDF file
$RADSDATAROOT/extra/sa/a/c001/sap0001c001.nc - netCDF file with alternative data fields
$RADSDATAROOT/extra/sa/a/c001/sap0001c001.ncml - ncML file for alternative aggregated dataset

Contents for the ncML file:
<netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
  <attribute name="title" type="string" value="Union of standard and alternative RADS files"/>
  <aggregation type="union">  
    <netcdf location="../../../../sa/a/c001/sap0001c001.nc"/>
    <netcdf location="sap0001c001.nc"/>
  </aggregation> 
</netcdf>
But I think I would still rather solve this within the RADS code itself, despite this solution being quite elegant.

-Remko

**Comment by remkos** [comment]
A solution for this was first implemented in [release v4.2.0](https://github.com/remkos/rads/tree/v4.2.0). Please read the release notes on how to implement this. It requires the "branch" option in the <data> tag.
