### ISSUE TITLE
Add GFZ SLCCI orbits version 11

### ISSUE THREAD

**Issue by remkos** [remkos/rads#77]
Sergei is to release his latest SLCCI orbits for Envisat, ERS-1, ERS-2, TOPEX, Jason-1, Jason-2 by the end of 2015. When available, add these to RADS, replacing previous GFZ orbit solutions.

**Comment by remkos** [comment]
The orbits were released in May 2016.
Now added to TX and PN.

**Comment by samroyston** [comment]
Given the low priority of this update, do you know the time frame for these orbits (and the GSFC std1504; #102) to be added to the RADS database for the Jason, Envisat and ERS missions? Thanks.

**Comment by remkos** [comment]
The GFZ SLCII orbits are to be released for all remaining missions (ERS-1/2, Envisat, Jason-1/2 in the upcoming "Nov 2017 updates". A minor update was made to the same orbits for TOPEX and Poseidon (issue #109).

**Comment by remkos** [comment]
All relevant missions patched. Upload finished 30 Nov 2017.
