### ISSUE TITLE
lon E/W conversion problem in rads2nc

### ISSUE THREAD

**Issue by ezaron** [remkos/rads#88]
There seems to be a problem with how degrees E, for values larger than 180, are handled.

When I execute this command,
rads2nc --sat c2/a --region 285.,305.,10.0,20.0 --ymd 20100611,20120715 --var time,lat,lon,sla
I receive a bunch of pass files, as expected, but the lon values are empty. I expected to receive pass files in which time,lat,lon, and sla are populated with valid data.

Conversely, when I execute this command,
rads2nc --sat c2/a --region -75.,-55.,10.0,20.0 --ymd 20100611,20120715 --var time,lat,lon,sla
the same pass files are generated, and they now contain valid data for all the fields.

-Ed

**Comment by remkos** [comment]
In case of Cryosat-2 this is actually expected. In the rads.xml file it says:

```
<var name="lon" field="301 3">
        <compress sat="c2">int4 1e-7</compress>
</var>
```

That means the longitudes are stored in 0.1 microdegrees as 4-byte integers. That means that numbers between 285 and 305 simply won't fit.
Either you use -75 to -55, as you already tried, or install a small configuration file rads.xml in ~/.rads or the directory in which you're running rads2nc with

```
<var name="lon">
        <compress sat="c2">int4 1e-6</compress>
</var>
```

or even shorter
`<compress var="lon" sat="c2">int4 1e-6</compress>`
provided you are up to date (have a version newer than 1 March 2016).

**Comment by ezaron** [comment]
Aha. Thank you. So the "compress" blocks refer to how the variable is represented in the output file, not how it is represented in the RADS database?
-Ed

**Comment by remkos** [comment]
In fact, both. In the netCDF files of the RADS database you will see for CryoSat:

```
        int lon(time) ;
                lon:_FillValue = 2147483647 ;
                lon:long_name = "longitude" ;
                lon:standard_name = "longitude" ;
                lon:units = "degrees_east" ;
                lon:scale_factor = 1.e-07 ;
                lon:field = 301s ;
                lon:comment = "East longitude relative to Greenwich meridian" ;
```

This too is regulated by the rads.xml file.

**Comment by remkos** [comment]
And I should add, if you use, e.g. --lon 285,305 then the longitudes are automatically converted to that range (modulo 360), even though in the files it is actually stored in the -180/180 range.

**Comment by ezaron** [comment]
If I use your suggestion in my local rads.xml file,
<compress var="lon" sat="c2">int4 1e-6</compress>,
how will the code know that the representation in the RADS database has not changed? Somehow the code is keeping track of the compression in the source netcdf, which would then differ from the declaration in the rads.xml?

Thanks again. I guess I should use separate --lon and --lat flags instead of the --region flag.

**Comment by remkos** [comment]
For the first part of your comment: RADS will adhere to what is written in the netCDF files ... I would almost say "of course". The scale_factor and add_offset in the file determine how the values are converted from their internal (often integer) representation to real numbers. When you use rads2nc (and in fact also how the database is created), it uses the info in the rads.xml file.

For the second part: --region is equivalent to using --lon and --lat. You can use what you feel like. All the following notations are equivalent:

```
--lon 285,350 --lat 10,20
--region 285.,305.,10.0,20.0
--lon=285/350 --lat=10/20
-R 285/305/10/20
-R285/305/10/20
```

And numerous other variations. This will all be explained in the user manual that I'm developing.
