### ISSUE TITLE
rads2nc has a memory allocation error when sending output to NetCDF & no data is available 

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#89]
The ASCII output of rads2nc works as expected. For example, selecting during a J2 safehold works:
rads2nc -Sj2 -C191 -P1,125 -Vsla 

But, sending the output to NetCDF produces a malloc error:
rads2nc -Sj2 -C191 -P1,125 -Vsla -otest.nc
rads2nc(56364,0x7fff7aad8300) malloc: **\* error for object 0x7fff63b28c68: pointer being freed was not allocated
**\* set a breakpoint in malloc_error_break to debug

**Comment by remkos** [comment]
I could duplicate the bug. I can imagine where it comes from. Should be relatively easy to fix.

**Comment by remkos** [comment]
Done. Please verify and close if satisfied.

**Comment by leuliett** [comment]
Verified.
