### ISSUE TITLE
Add DAC-ERA

### ISSUE THREAD

**Issue by leuliett** [remkos/rads#93]
http://www.aviso.altimetry.fr/en/data/products/auxiliary-products/atmospheric-corrections/description-atmospheric-corrections.html

Within the Climate Change Initiative (CCI) project (ESA), a specific DAC-ERA has been computed for climate applications using the ECMWF ERA-INTERIM reanalysis on the 1991-2014 period. This DAC-ERA is significantly improved for the first years of altimetry (Carrère et al.,"Major improvement of altimetry sea level estimations using pressure derived corrections based on ERA-interim atmospheric reanalysis", to be submitted to Ocean Science)

**Comment by remkos** [comment]
Requested data from L. Carrere.

**Comment by remkos** [comment]
All mission data are updated for the years 1991-2015, adding variable inv_bar_mog2d_era. Upload to be done soon.

**Comment by remkos** [comment]
Upload finished 30 Nov 2017.
