### ISSUE TITLE
Extend GOT 4.10c model

### ISSUE THREAD

**Issue by remkos** [remkos/rads#95]
Ed Zaron has been extrapolating the GOT 4.10.c model as to provide a better coverage of the coastal regions. His work is supported by National Geospatial Agency (Grant award #HM0177-13-1-0008, "Improving Coastal Marine Gravity").

See Ed Zaron's [web page](http://web.cecs.pdx.edu/~zaron/pub/GOT-e.html).

**Comment by ezaron** [comment]
Hi Remko,
I wonder if you are using any of the GOT models extrapolated to the coastline in RADS? I heard that the Jason-2 GDR was now being produced this way, but I haven't checked what they've done.
-Ed

**Comment by remkos** [comment]
The use of the extrapolated GOT4.10 model is addressed by commit 75ea43349352b3505b6826d86ba028d0a3318d01
All missions patched. Upload finished 30 Nov 2017.
