### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ezaron** [remkos/rads#96]
Hi Remko,

I just tried to install a fresh checkout of RADS4 and encountered a problem at the "make install" stage:

./configure --prefix=/home/ezaron/opt
make
make install

Everything seems to go smoothly except the "make install". Output is cut-and-pasted below. This is on a Linux machine (Linux baburu 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux; Ubuntu 16.04; shell is /bin/bash, but I also tried ksh and got the same result).

make  -C src install  
make[1]: Entering directory '/media/Data/LaCie1TB/LaCie1TB/RADS/rads-master/src'  
/usr/bin/install -c -d /home/ezaron/opt/lib /home/ezaron/opt/include /home/ezaron/opt/bin  
/usr/bin/install -c -m 644 librads.a /home/ezaron/opt/lib  
/usr/bin/install -c -m 644 rads_time.mod rads_misc.mod rads_grid.mod rads_geo.mod rads_math.mod rads_netcdf.mod xmlparse.mod rads.mod rads3.mod /home/ezaron/opt/include  
/usr/bin/install -c rads2asc rads2adr rads2nc rads2grd radsstat radscolin radsxogen radsxoconv radsxolist rads_test radsreconfig rads_sample rads3test radsvar /home/ezaron/opt/bin  
/usr/bin/install -c rads-config /home/ezaron/opt/bin  
for p in rads2xadr rads2xgf; do ( cd /home/ezaron/opt/bin ; ln -s -f rads2adr $p ) ; done  
for p in radsxostat; do ( cd /home/ezaron/opt/bin ; ln -s -f radsxolist $p ) ; done  
for p in rads2asc4 radscolin4 radsstat4 rads2grd4; do ( cd /home/ezaron/opt/bin ; ln -s -f ${p/4/} $p ) ; done  
/bin/sh: 1: Bad substitution  
/bin/sh: 1: Bad substitution  
/bin/sh: 1: Bad substitution  
/bin/sh: 1: Bad substitution  
Makefile:52: recipe for target 'install' failed  
make[1]: **\* [install] Error 2  
make[1]: Leaving directory '/media/Data/LaCie1TB/LaCie1TB/RADS/rads-master/src'  
Makefile:43: recipe for target 'src' failed  
make: **\* [src] Error 2

**Comment by remkos** [comment]
This problem appears to be related to an incorrect assumption that the shell in which the commands are executed is "bash". A workaround is to run "make install" in a bash shell, or run "make SHELL=bash install".

I will make a patch to avoid this issue without forcing the use of bash.

**Comment by remkos** [comment]
Fix tested in sash, ksh, zsh. I assume this works too in the traditional bourne shell.
Ed, please test and close if it works for you.

**Comment by ezaron** [comment]
Hi Remko,

I tested your fix, and it works, but this is confusing to me since my 
login shell is /bin/bash.

The real issue is apparently that gnumake does not use the user's SHELL 
to run its own commands:

https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html

The "for p in" syntax used inside the install target in the makefile 
under /src is apparently the place where make needs bash. Another fix is 
to put "SHELL=/bin/bash" in this makefile after, say, "include 
../config.mk".

-Ed

**Comment by remkos** [comment]
Dear Ed,

While your suggestion is certainly valid, I choose to avoid relying on bash (some may not have it installed by default, or not in /bin) but instead used a syntax that is supported by seemingly all bourne-type shells.
That is, I now use ${p%4} instead of ${p/4/}. And it is one character shorter :)
